# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 10:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appProfile', '0005_companyprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='uploads/notifications/')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('affected_users', django.contrib.postgres.fields.jsonb.JSONField(default={'user': [{'id': 1}]})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProfile.Profile')),
            ],
        ),
    ]
