# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 21:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='e-TPO', max_length=32)),
                ('description', models.TextField(max_length=500)),
                ('avatar', models.ImageField(upload_to='uploads/avatar/company/')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('fcm_token', models.TextField(blank=True, max_length=32)),
                ('roll_no', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, upload_to='uploads/avatar/user/')),
                ('resume', models.FileField(blank=True, upload_to='uploads/resume/')),
                ('social', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('projects', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('achievements', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
