# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
    ]
