# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0004_auto_20180125_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
