# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0005_companyprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
