# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 09:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(default={'cpi': 5.0, 'sem': 5})),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
                ('rounds', django.contrib.postgres.fields.jsonb.JSONField(default={'no': 1, 'rounds_details': [{'description': 'Sample description', 'step': 1, 'title': 'Sample round detail'}, {'description': 'Sample description', 'step': 1, 'title': 'Sample round detail'}]})),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProfile.CompanyProfile')),
            ],
        ),
    ]
