# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 09:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0001_initial'),
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementSessionRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_status', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='placementsession',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementsessionregistration',
            name='placementSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.PlacementSession'),
        ),
        migrations.AddField(
            model_name='placementsessionregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProfile.Profile'),
        ),
    ]
